### Pytorch as high performance linear algebra library
PyTorch is a library for linear algebra, other components of PyTorch are a higher-level abstraction for neural networks that you build upon the lower level linear algebra.

PyTorch can compute on a GPU, CPU, or other advanced compute device. If you are using a Mac, PyTorch is now adding additional support for Apple silicone (M1, M2, M3, etc). For apple support we will use Metal Performance Shaders (MPS). For this course, we assume you will utilize a GPU (cuda), CPU, or MPS. The following code detects the available device and defines the device variable that the following code will use for computation. For parts of this course that I know do not work for MPS, we will fall back to CPU. CUDA is an NVIDIA standard for accessing GPU capabilities.

In [2]:
import torch

In [3]:
# selecting a device 
has_mps = torch.backends.mps.is_built()
device = "mps" if has_mps else "cuda" if torch.cuda.is_available() else "cpu"
print(device)

cuda


In [4]:
# Create a Constant op that produces a 1x2 matrix.  The op is  added as a node to the default graph.

# The value returned by the constructor represents the output of the Constant op.
matrix1 = torch.tensor([[3.0, 3.0]], device=device)

# Create another Constant that produces a 2x1 matrix.
matrix2 = torch.tensor([[2.0], [2.0]], device=device)

# Create a Matmul op that takes 'matrix1' and 'matrix2' as inputs.
# The returned value, 'product', represents the result of the matrix multiplication
product = torch.mm(matrix1, matrix2)

print(product)
print(float(product))

tensor([[12.]], device='cuda:0')
12.0


This example multiplied two PyTorch tensors. You can see that we created each tensor on the appropriate device, either the GPU or CPU. Next, we will see how to subtract a constant from a variable.

In [5]:
x = torch.tensor([[1.0], [2.0]], device=device)
a = torch.tensor([[3.0], [3.0]], device=device)

# subtracting 'a' from 'x' 
sub = torch.subtract(x, a)
print(sub)

tensor([[-2.],
        [-1.]], device='cuda:0')


Of course, variables are only helpful if we can change their values. The program can accomplish this change in value by calling the assign function. To use Numpy, we must first bring the tensor back to the CPU with the cpu() command. Next, we call numpy() to access the tensor as a Numpy array. If we were already on the CPU, this function has no effect and returns the already CPU-resident tensor.

In [6]:
x[0] = 4.0
x[1] = 6.0

The program can now perform the substraction with this new value

In [7]:
sub = torch.subtract(x, a)
print(sub)
print(sub.cpu().numpy())

tensor([[1.],
        [3.]], device='cuda:0')
[[1.]
 [3.]]
