In [2]:
import torch
import numpy as np

In [3]:
torch.__version__

'2.2.2+cpu'

In [6]:
arr = np.array(range(1,6))
print(arr)

[1 2 3 4 5]


In [9]:
# create a tensor pointing the same memory location than the np array
x = torch.from_numpy(arr)
# torch.as_tensor(arr)
type(x)

torch.Tensor

In [10]:
# creating a torch 2d tensor from nparray (pointing the same memory location)
arr2d = np.arange(0.0, 12.0).reshape(4, 3)

In [11]:
x2 = torch.from_numpy(arr2d)

In [12]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [13]:
arr[0] = 99

In [14]:
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [17]:
# creating a working copy
my_arr = np.arange(0,10)
my_tensor = torch.tensor(my_arr) #integer tensor
my_tensor_f = torch.Tensor(my_arr) #flotating point tensor

In [20]:
my_tensor.dtype

torch.int32

In [19]:
my_tensor_f.dtype

torch.float32

In [23]:
# creating tensors with torch
# uninitialized tensor (block of memory of size of the tensor)
torch.empty(4,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [25]:
# zeros tensor 
torch.zeros(4,2, dtype=torch.int32)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]], dtype=torch.int32)

In [4]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.linspace(2, 20, 10)

tensor([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [13]:
torch.arange(0, 18, 2).reshape(3, 3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [14]:
# changing precision 
my_ten = torch.tensor([1,2,3])
print(my_ten.dtype)
my_ten.type(torch.int32)

torch.int64


tensor([1, 2, 3], dtype=torch.int32)

In [15]:
torch.rand(4,3) # random samples from an equal distribution between 0 and 1

tensor([[0.7108, 0.6421, 0.3419],
        [0.9385, 0.5377, 0.0802],
        [0.2981, 0.8277, 0.1546],
        [0.8588, 0.9309, 0.1958]])

In [16]:
torch.randn(4,3) # normal standard distribution between -1 and 1 (std = 1)

tensor([[-0.7729,  0.9328, -0.5099],
        [-0.9252,  1.7193, -1.5759],
        [-1.2990,  0.5646, -0.3330],
        [-0.1715, -1.3043, -0.4477]])

In [22]:
x = torch.randint(low=0, high=10, size=[4,3], dtype=torch.float32)

In [23]:
torch.randn_like(x)

tensor([[-1.8707, -0.5673, -0.3799],
        [-0.0902,  0.4885, -1.0111],
        [ 0.2238, -0.7931,  2.0462],
        [ 0.6534, -0.9778, -0.1130]])

In [24]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])