In [22]:
import torch
import numpy as np

In [23]:
x = torch.arange(6).reshape(3,2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [24]:
type(x[1,1])

torch.Tensor

In [25]:
# returns a 1d tensor
x[:,1]

tensor([1, 3, 5])

In [26]:
# returns a column tensor (column vector) (used often)
x[:, 1:]

tensor([[1],
        [3],
        [5]])

In [27]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [28]:
z = x.view(2, 5)

In [29]:
y = x.reshape(2, 5)

In [30]:
x[0] = 9999

In [31]:
print(z)
print(y)

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])
tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])


In [32]:
torch.cuda.is_available()

True

In [42]:
torch.cuda.get_device_name(0)

'NVIDIA GeForce GTX 1070'

In [34]:
a = torch.arange(3)
b = torch.arange(3)

In [35]:
c = torch.add(a, b)

In [36]:
print(c)

tensor([0, 2, 4])


In [37]:
print(a)
a.mul_(b) # re-assigns the value of a with the multiplication of a and b
print(a)

tensor([0, 1, 2])
tensor([0, 1, 4])


In [38]:
x = torch.randint(0, 10, (3, 3))
y = torch.randint(0, 10, (3, 3))
print(x, y)

tensor([[0, 6, 6],
        [9, 9, 5],
        [4, 0, 9]]) tensor([[6, 4, 8],
        [6, 5, 0],
        [6, 7, 8]])


In [39]:
# matrix multiplication
z = torch.mm(x, y) #also valid a @ b
print(z)

tensor([[ 72,  72,  48],
        [138, 116, 112],
        [ 78,  79, 104]])


In [40]:
# dot product
z_dot = torch.dot(a, b)
print(z_dot)

tensor(9)


In [41]:
# euclidean norm
a = torch.randn(3, 3)
a.norm()

tensor(3.7957)

In [43]:
# set the random seed for numpy and pytorch both to 42
np.random.seed(42)
torch.manual_seed(42)

In [44]:
arr = np.random.randint(0, 5, 6)

In [45]:
print(arr)

[3 4 2 4 4 1]


In [46]:
# create an x tensor from arr
x = torch.from_numpy(arr)
x

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)

In [49]:
# Change the dtype of x from 'int32' to 'int64'
x = x.type(torch.int64)
x.type()

'torch.LongTensor'

In [50]:
# reshape x into a 3x2 tensor
x = x.reshape(3, 2)

In [52]:
# return the right-hand column of tensor x as a column tensor
x[:, 1:]

tensor([[4],
        [4],
        [1]])

In [53]:
# without changing x, return a tensor of square values of x
x ** 2

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

In [54]:
# create a tensor "y" with the same number of elements as x that can be matrix-multiplied with x. Use torch directly to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).
y = torch.randint(0, 5, (2,3))

In [55]:
# find the matrix product of x and y
x.mm(y)

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])