In [1]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# computational dynamic graph is a ds that helps tracking changes in a tensor using graphs ds. The next code sets up computational tracking on a tensor
x = torch.tensor(2.0, requires_grad=True)

In [3]:
# defining a tensorial function 
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [8]:
# numerical differentiation
def f(x):
    return 3*x**2 - 4*x

def numerical_lim(f, x, h):
    return (f(x+h)-f(x))/h

h = 0.1
for i in range(7):
    print(f'h={h: 6f}, numerical limit = {numerical_lim(f, 1, h):.6f}')
    h *= 0.1

h= 0.100000, numerical limit = 2.300000
h= 0.010000, numerical limit = 2.030000
h= 0.001000, numerical limit = 2.003000
h= 0.000100, numerical limit = 2.000300
h= 0.000010, numerical limit = 2.000030
h= 0.000001, numerical limit = 2.000003
h= 0.000000, numerical limit = 2.000000


In [2]:
x = torch.arange(4.0, requires_grad=True)
print(x.grad) # the default value is None

None


In [3]:
y = torch.dot(x,x) # f(x_vector) = x . x = (||x||)^2 = (sqrt(x1^2 + ... xn^2))^2 = x1^2 + ... xn^2
print(y)

tensor(14., grad_fn=<DotBackward0>)


In [4]:
y.backward()

In [6]:
print(x)
print(x.grad)

tensor([0., 1., 2., 3.], requires_grad=True)
tensor([0., 2., 4., 6.])


In [7]:
x.grad == 2*x # check if 2*x is the general vector function solution of the operation grad(x_vector)

tensor([True, True, True, True])

In [8]:
# another example 
# f(x_vector) = x1 + x2 + ... + xn
# IMPORTANT!!! torch accumulates the gradient, to reset the gradient to zeros
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [9]:
print(x.grad)

tensor([0., 0., 0., 0.])


In [10]:
print(x)

tensor([0., 1., 2., 3.], requires_grad=True)


In [11]:
# the derivative of a variable with respect to itself: dx/dx == 1
y = x.sum() # f(x_vector) = x1 + x2 + ... + xn
y.backward()
print(x.grad)

tensor([1., 1., 1., 1.])


In [ ]:
# backward for non-scalar variables