In [1]:
import numpy as np

## Numpy basics
#### Convert From python list to numpy Array

In [2]:
mylist = [1, 2, 3]
type(mylist)

list

In [3]:
np_arr = np.array(mylist)
type(np_arr)

numpy.ndarray

#### Create numpy matrices from python list of lists

In [4]:
# A list o tree lists in python becomes a 3x3 matrix with np.array
my_list = [[1,2,3],[4,5,6],[7,8,9]]
np_matrix = np.array(my_list)
print(np_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
np_matrix.shape

(3, 3)

#### Create a np.array from 0 to 11 

In [6]:
# numpy array from 0 to 11 [0, 12) excluding 12 including 0
arrange = np.arange(0, 12, 1)
print(arrange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


#### Create an array of zeroes 

In [7]:
# type of zeros is float
npz = np.zeros((2,2))
print(npz)
print(type(npz[0][0]))

[[0. 0.]
 [0. 0.]]
<class 'numpy.float64'>


#### Creating an array of ones

In [8]:
np_ones = np.ones((2,2))
print(np_ones)

[[1. 1.]
 [1. 1.]]


#### Numpy broadcasting

In [9]:
np.ones((3,3))*4

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

#### Evenly spaced np array

In [10]:
np.linspace(0,10,11) 

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

#### Create an identity matrix

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


#### Create a Random sample of floats from a uniform distribution over zero and one 
Every number between 0, and 1 has the same probability of getting chosen

In [12]:
np.random.rand(4,4)

array([[0.48161977, 0.01349597, 0.64150274, 0.97859476],
       [0.17197324, 0.31623908, 0.75742129, 0.03467791],
       [0.4671564 , 0.49302062, 0.64414322, 0.47998974],
       [0.95642671, 0.3686915 , 0.86404386, 0.99683575]])

#### Create a random sample from a normal distribution over zero and one 
A normal distribution has a mean of (0) and standard deviation at 1. This means that the numbers returned are between -1 and 1

In [13]:
np.random.randn(3,3)

array([[ 0.10891139,  0.68589354,  0.98668794],
       [ 0.88181763, -1.53424102,  0.05474472],
       [-0.20297039, -1.02414402, -0.74180231]])

#### Random numpy array of integers 

In [14]:
arr = np.random.randint(0, 50, 25)
arr

array([48, 19, 33, 12, 21, 24, 24, 19, 47, 10, 26,  5, 39, 28, 41, 47, 24,
       15, 35, 45, 32, 44,  4, 31, 38])

#### Reshaping the 1D integers array to (a, b) matrix (rows, cols)

In [15]:
arr_m = arr.reshape(5, 5)
print(arr_m)

[[48 19 33 12 21]
 [24 24 19 47 10]
 [26  5 39 28 41]
 [47 24 15 35 45]
 [32 44  4 31 38]]


#### Return the maximum value of an array

In [16]:
arr.max()

48

#### Return the minimum value of an array

In [17]:
arr.min()

4

#### Return the datatype of the values contained in an array

In [18]:
arr.dtype

dtype('int32')

## Python and numpy slicing 
### Basic String slicing 
Python uses the next sintax to make slices in iterables and collections: 
$$L[start:stop:step]$$ 

In [19]:
str_slice = "Welcome Python"

#### Select the first element of the string

In [20]:
str_slice[0]

'W'

#### Select the last element of the string

In [21]:
str_slice[-1]

'n'

#### Select all, starting with index = 3

In [32]:
str_slice[3:]

'come Python'

#### Select all until the index = 5 (not including it)

In [33]:
str_slice[:5]

'Welco'

#### Select from index = 3 to index = 12 (not including it)

In [34]:
str_slice[3:12]

'come Pyth'

#### Select all the elements two by two
To make certain slices there are many possible ways 

In [35]:
if str_slice[::2] == str_slice[0::2] == str_slice[0:14:2]:
    print(True)
str_slice[::2]

True


'WloePto'

#### Select all the elements in the string

In [46]:
if str_slice[0:14] == str_slice[:] == str_slice[0:] == str_slice[0:14:1]:
  print(True)
str_slice[:]

True


'Welcome Python'

#### Select all, from right to left, starting in index = 3
This is equivalent to select all less the tree last elements

In [36]:
str_slice[:-3]

'Welcome Pyt'

#### Select all until the index = 5 (not including it) but from right to left

In [38]:
str_slice[-5:]

'ython'

### *Basic Numpy array slicing*

In [40]:
arr = np.random.randint(0, 50, 25)
arr

array([47, 13, 21, 37,  7,  0, 35, 29, 16,  9, 35, 35, 19,  2,  9, 19, 22,
        6, 21, 17, 23, 18, 23, 30, 43])

#### Select the element with the index = 10

In [41]:
arr[10]

35

#### Select the first 10 elements

In [42]:
arr[0:10]

array([47, 13, 21, 37,  7,  0, 35, 29, 16,  9])

#### Select all starting with the index = 15
Equivalent to select the last 10 elements

In [43]:
arr[15:]

array([19, 22,  6, 21, 17, 23, 18, 23, 30, 43])

### *Multidimensional numpy array slicing*

In [44]:
arr2D = np.random.randint(0, 50, 25).reshape(5,5)
arr2D

array([[40, 30, 35,  7, 27],
       [ 8,  7, 39, 42, 33],
       [ 1, 12, 24, 26, 19],
       [ 5,  5, 48, 29, 16],
       [36, 27, 49, 20, 23]])

#### Select rows from a np.array matrix with *indices*

In [45]:
first_row = arr2D[0]
last_row = arr2D[-1]
print(f'first_row: {first_row}, last_row: {last_row}')

first_row: [40 30 35  7 27], last_row: [36 27 49 20 23]


#### Select rows from a np.array matrix with *slices*

In [47]:
# from the first row element, element with index = 0, select all (:) the column elements
first_row = arr2D[0, :]
# from the last row element (index = -1), select all (:) the column elements
last_row = arr2D[-1, :]
print(f'first_row: {first_row}, last_row: {last_row}')

first_row: [40 30 35  7 27], last_row: [36 27 49 20 23]


#### Select columns of a np.array matrix

In [49]:
# from the matrix select all the rows (:) and from all the rows select the first (0) column element
first_col = arr2D[:, 0]
first_col

array([40,  8,  1,  5, 36])

#### Convert in a column vector a column of a np.array matrix

In [50]:
first_col = arr2D[:, 0].reshape(-1, 1)
first_col

array([[40],
       [ 8],
       [ 1],
       [ 5],
       [36]])

#### Select sub-matrices fom a np.array matrix

In [53]:
# from the first (0) to the index = 2 (not including it) rows, select the column elements from i=1 to i=3 (not including it)
sub_matrix = arr2D[0:2, 1:3]
# equivalent form
sub_matrix_2 = arr2D[:2, 1:3]
if sub_matrix.all() == sub_matrix_2.all():
    print(sub_matrix)

[[30 35]
 [ 7 39]]
