In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
print(arr**2)

[  0   1   4   9  16  25  36  49  64  81 100]


In [4]:
# numpy returns 1/0 as infinity not as an error
1/arr

C:\Users\usuario\AppData\Local\Temp\ipykernel_5852\1163317758.py:2: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [5]:
# numpy returns 0/0 as not a number nan
arr/arr

C:\Users\usuario\AppData\Local\Temp\ipykernel_5852\4116947663.py:2: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [6]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [7]:
# sum of all members
arr.sum()

55

In [8]:
arr.mean()

5.0

In [9]:
arr.max()

10

In [13]:
arr_2d = np.random.randint(0, 50, 12).reshape(3,4)
print(arr_2d)

[[ 8 21 40 19]
 [15 11  8 41]
 [34 43  6  9]]


In [12]:
# sum of all members
arr_2d.sum()

289

In [14]:
# give the sum across the rows
arr_2d.sum(axis=0)

array([57, 75, 54, 69])

In [15]:
# give the sum across the columns
arr_2d.sum(axis=1)

array([88, 75, 92])