In [24]:
import numpy as np
import random
import sympy as sp

## List and Array Comprehension
In python list comprehension is a compact syntax that allow the population of python lists using loops in a single instruction. For numpy arrays exists the same syntax. With the C++ optimization of numpy the array comprehension operations are faster than the lists comprehension operations.  

### Basic python list comprehension
#### Squaring a list of numbers

In [1]:
nums = [1, 2, 3, 4, 5, 6]
squares = [x**2 for x in nums]
squares

[1, 4, 9, 16, 25, 36]

#### Filtering Even Numbers from a list
The lists can be filtered with the use of contidionals 

In [2]:
nums = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_nums = [x for x in nums if x % 2 == 0]
even_nums

[2, 4, 6, 8, 10]

#### Creating a list of tuples with list comprehension
For the construction of lists of pairs (model_result, expected_result) list comprehension can be used along with ´zip()´.

In [4]:
letters = ['a', 'b', 'c', 'd']
nums = [1, 2, 3, 4]
pairs = [(letter, number) for letter, number in zip(letters, nums)]
pairs

[('a', 1), ('b', 2), ('c', 3), ('d', 4)]

#### Flattening a nested list into a single list

In [5]:
nested_list = [[1, 2], [3, 4], [5, 6]]
flat_list = [item for sublist in nested_list for item in sublist]
flat_list

[1, 2, 3, 4, 5, 6]

#### Mapping categorical data to binary values

In [22]:
categories = ['cat', 'dog', 'horse', 'mouse', 'cat']
binary_values = [1 if animal == 'cat' else 0 for animal in categories]
binary_values

[1, 0, 0, 0, 1]

#### Mapping a function for each element of a list

In [6]:
def double(x):
    return x * 2

numbers = [1,2,3,4,5,6,7,8,9,10]
doubled_nums = [double(x) for x in numbers]
doubled_nums

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

#### Applying a transformation based on a condition

In [7]:
nums = [1, -2, 3, -4, 5, 6, -7, 8, -9, -10]
positive_squares = [x**2 if x > 0 else 0 for x in nums]
positive_squares

[1, 0, 9, 0, 25, 36, 0, 64, 0, 0]

#### Extracting values from a dictionary of lists

In [8]:
data = {'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]}
flat_data = [item for sublist in data.values() for item in sublist]
flat_data

[1, 2, 3, 4, 5, 6, 7, 8, 9]

#### Filtering and Transforming simultaneously

In [10]:
numbers = list(range(10))
even_squares = [x**2 for x in numbers if x % 2 == 0]
even_squares

[0, 4, 16, 36, 64]

#### Cartesian products with multiple loops

In [11]:
letters = ['a', 'b']
numbers = [1, 2, 3]
cartesian_product = [(letter, number) for letter in letters for number in numbers]
cartesian_product

[('a', 1), ('a', 2), ('a', 3), ('b', 1), ('b', 2), ('b', 3)]

#### Feature normalization with list comprehension
Normalizing the data in a scale from 0 to 1

In [12]:
data = [34, 56, 23, 89, 90]
min_val, max_val = min(data), max(data)
normalized_data = [(x-min_val)/(max_val - min_val) for x in data]
normalized_data

[0.16417910447761194, 0.4925373134328358, 0.0, 0.9850746268656716, 1.0]

#### List of One-hot encoding Labels
When working with categorical data, you often need to convert categorical labels into a one-hot encoded format 

In [14]:
labels = [0, 1, 2, 0, 1]
n_classes = len(set(labels))
one_hot_labels = [[1 if i == label else 0 for i in range(n_classes)] for label in labels]
one_hot_labels

[[1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 0, 0], [0, 1, 0]]

#### Generating synthetic (x, y) data for trainings

In [16]:
x = [i for i in range(100)]
y = [2*i + random.uniform(-10, 10) for i in x]
print(x)
print(y)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[3.044254621243283, 9.23258511263532, 2.3932027683228227, 13.009268914537728, 2.2481179664468716, 15.542011253811143, 4.524689112450278, 4.7840570237936255, 18.335017501920284, 14.211353788588003, 22.214769694884065, 26.296018888888202, 29.75178010126664, 25.30853930443319, 30.27692456079211, 32.09770303609123, 30.545023355827617, 36.930449548602006, 28.912689568349492, 39.58296377274885, 37.40049580745577, 45.58288747636053, 47.33469013729059, 52.48294332702211, 38.56312000341891, 49.91973781111079, 61.37352450512512, 62.8367505505436, 61.91570848065281, 53.277553142905596, 59.89902661447209, 60.25315

### Numpy Array comprehension

#### Element-Wise multiplication
Element-wise operations are element-by-element operations among arrays like the *Hadamard Product*

In [17]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])
product = np.array([x*y for x, y in zip(array1, array2)])
product

array([5, 8, 9, 8, 5])

#### np.array filtering
Like python lists the np.arrays can be filtered by conditions

In [19]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_nums = np.array([x for x in numbers if x % 2 == 0])
even_nums

array([ 2,  4,  6,  8, 10])

#### np.array comprehension for function mapping (vectorizing a function)
Applies the ReLU activation function to the incoming vector input. 

In [21]:
def ReLU(x):
    return np.maximum(0.0, x)

input = np.random.uniform(-1.0, 1.0, 10)
neuron_output = np.array([ReLU(x) for x in input])
neuron_output

array([0.        , 0.        , 0.        , 0.        , 0.83446335,
       0.        , 0.04713061, 0.95246176, 0.88439251, 0.        ])

#### Defining a identity matrix with array comprehension

In [27]:
size = 4
identity_matrix = np.array([[1 if i == j else 0 for j in range(size)] for i in range(size)])

sympy_matrix = sp.Matrix(identity_matrix)
sympy_matrix

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]])

#### Normalizing an array
Transform the data in a range from 0 to 1

In [28]:
data = np.array([1.0, 3.0, -2.4 , 4.5, -40.5, 0.4, 1.0, 3.5])
min_val, max_val = data.min(), data.max()
normalized_data = np.array([(x - min_val)/(max_val - min_val) for x in data])
normalized_data

array([0.92222222, 0.96666667, 0.84666667, 1.        , 0.        ,
       0.90888889, 0.92222222, 0.97777778])

#### Batch Processing Data
For the training algorithms the data is usually splitted in batchs of data. In this case a flat np.array with 100 elements will be converted in a np.matrix of 10 samples.

In [29]:
data = np.arange(100)
batch_size = 10
batches = np.array([data[i:i + batch_size] for i in range(0, len(data), batch_size)])
# batches = np.array_split(batches, batch_size)
batches

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### Combining both list and array comprehension
#### *Initializing Deep Neural Networks Parameters*
For randomly set the values of the weights or the biases for a *Deep Neural Network* at the begining of a training task list comprehension can be used alog with numpy arrays

In [32]:
# layers and number of neurons per layer
first_layer = 6
hidden_layer = 8
output_layer = 10

layer_sizes = [first_layer, hidden_layer, output_layer]

weights = [np.random.randn(input_size, output_size) for input_size, output_size in zip( layer_sizes[:-1], layer_sizes[1:])]

print(f'weights of the neuron #{1} in the {1} layer to the {2} layer: {weights[0][0]}')

weights of the neuron #1 in the 1 layer to the 2 layer: [ 0.27513782  0.32307218 -0.49031781  0.71647226 -0.73694017  1.16699559
  1.23115957  1.41889196]
