In [44]:
import numpy as np

Convert From python list to numpy Array

In [45]:
mylist = [1, 2, 3]
type(mylist)

list

In [46]:
np_arr = np.array(mylist)
type(np_arr)

numpy.ndarray

Create numpy matrices from python list of lists

In [47]:
# A list o tree lists in python becomes a 3x3 matrix with np.array
my_list = [[1,2,3],[4,5,6],[7,8,9]]
np_matrix = np.array(my_list)
print(np_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
np_matrix.shape

(3, 3)

Create a np array from 0 to 11 

In [49]:
# numpy array from 0 to 11 [0, 12) excluding 12 including 0
arrange = np.arange(0, 12, 1)
print(arrange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


Create an array of zeroes 

In [50]:
# type of zeros is float
npz = np.zeros((2,2))
print(npz)
print(type(npz[0][0]))

[[0. 0.]
 [0. 0.]]
<class 'numpy.float64'>


Creating an array of ones

In [51]:
np_ones = np.ones((2,2))
print(np_ones)

[[1. 1.]
 [1. 1.]]


Numpy broadcasting

In [52]:
np.ones((3,3))*4

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

Evenly spaced np array

In [53]:
np.linspace(0,10,11) 

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Create an identity matrix

In [54]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


Random sample of floats from a uniform distribution over zero and one. Every number between 0, and 1 has the same probability of getting chosen

In [55]:
np.random.rand(4,4)

array([[0.83031113, 0.57900048, 0.96421047, 0.82977121],
       [0.45194114, 0.38333013, 0.76713805, 0.63828502],
       [0.12196189, 0.72504519, 0.99527577, 0.89670107],
       [0.76063332, 0.91004796, 0.45748529, 0.91182629]])

Create a random sample from a normal distribution over zero and one. A normal distribution has a mean of (0) and standard deviation at 1. This means that the numbers returned are between -1 and 1.

In [56]:
np.random.randn(3,3)

array([[-0.10117109, -0.83377584,  0.44472989],
       [ 0.06571121,  0.82880156, -1.73733678],
       [-0.04585798,  1.19008352,  0.71591051]])

Random numpy array of integers 

In [57]:
arr = np.random.randint(0, 50, 25)
arr

array([27, 34, 13, 11, 19,  9, 45, 31, 35, 20, 22, 19, 47, 13,  7, 46, 38,
       37, 36, 38, 43, 20,  5, 31,  0])

 Reshaping the 1D integers array to (a, b) matrix (rows, cols)

In [58]:
arr_m = arr.reshape(5, 5)
print(arr_m)

[[27 34 13 11 19]
 [ 9 45 31 35 20]
 [22 19 47 13  7]
 [46 38 37 36 38]
 [43 20  5 31  0]]


Return the maximum value of an array

In [59]:
arr.max()

47

Return the minimum value of an array

In [60]:
arr.min()

0

Return the datatype of the values contained in an array

In [61]:
arr.dtype

dtype('int32')

Selecting elements by index (1D)

In [62]:
# array index notation
print(arr)
print(arr[10])

[27 34 13 11 19  9 45 31 35 20 22 19 47 13  7 46 38 37 36 38 43 20  5 31
  0]
22


In [63]:
# first ten elements
print(arr)
print(arr[0:10])

[27 34 13 11 19  9 45 31 35 20 22 19 47 13  7 46 38 37 36 38 43 20  5 31
  0]
[27 34 13 11 19  9 45 31 35 20]


In [64]:
# last five elements
print(arr[20:]) 

[43 20  5 31  0]


Selecting elements by index (2D)

In [65]:
arr55 = np.random.randint(0, 50, 25).reshape(5,5)

In [66]:
print(arr55)

[[ 6 30  0  1 34]
 [ 7 11 34 32 17]
 [20 11 37 28 27]
 [18  1 38 41 16]
 [ 0 23 18 22 22]]


In [67]:
# numpy row column selection arr[row][col] arr[row, col]
arr55[0,3]

1

In [68]:
# slice with row col selection
arrsele = arr55[:2,1:]
print(arrsele)

[[30  0  1 34]
 [11 34 32 17]]


Selecting elements by conditionals

In [69]:
# conditional selection
print(arr > 4)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False]


In [70]:
bool_arr = arr < 6
arr[bool_arr]

array([5, 0])